openapi: 3.1.0
info:
  title: Описание API сервера проекта «Шесть городов».
  description: |-
    * API для работы с предложениями об аренде недвижимости, комментариями, управлением пользователями и избранными предложениями.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  tags:
  - name: offers
    description: Предложение об аренде недвижимости, включает в себя всю необходимую информацию о жилье.
  - name: favorites
    description: Управление списком избранных предложений пользователя. Позволяет авторизованным пользователям сохранять понравившиеся предложения для быстрого доступа в будущем.
  - name: comments
    description: Работа с комментариями, оставленными пользователями к конкретным предложениям об аренде недвижимости. Комментарии позволяют пользователям обмениваться мнениями и впечатлениями о предложениях.
  - name: users
    description: Управление учетными записями пользователей сервиса. Пользователи могут выступать как в роли арендодателей, так и арендаторов, предоставляя или ища предложения об аренде недвижимости.
  - name: cities
    description: Предоставляет информацию о городах, в которых доступны предложения об аренде.
  version: 2.0.0
